### ISSUE TITLE
Uploading documents stay on redirecting phase

### ISSUE THREAD

**Issue by JasonMKY** [Manice18/chatdocu#1]
Document doesn't load and just stays on redirecting phase:

![image](https://github.com/Manice18/chatdocu/assets/104327713/5cec64c4-fe7b-4350-9edb-7f63cf303de8)

How to fix?

**Comment by Manice18** [comment]
My Pinecone has stopped 🥲
You can get a paid version of Pinecone

**Comment by baxsm** [comment]
Use filter and it'll be fine
[Ref](https://github.com/baxsm/quill-nextjs/blob/f1df7d70b78a1eb99cf4687e6f088a5e4c4feaa6/app/api/uploadthing/core.ts#L95)
